"""Add text to User Post

Revision ID: 5833cfabbe64
Revises: 9e5a62338125
Create Date: 2021-08-08 10:28:53.183802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5833cfabbe64'
down_revision = '9e5a62338125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpost', sa.Column('text', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpost', 'text')
    # ### end Alembic commands ###
