"""Add created_dt to User Post

Revision ID: 751d9f2e5ba9
Revises: 5833cfabbe64
Create Date: 2021-08-08 10:35:03.594823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751d9f2e5ba9'
down_revision = '5833cfabbe64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpost', sa.Column('created_dt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpost', 'created_dt')
    # ### end Alembic commands ###
