"""Add foreign key to User Post

Revision ID: 9e5a62338125
Revises: 53bdd3f4b854
Create Date: 2021-08-07 15:08:21.128815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5a62338125'
down_revision = '53bdd3f4b854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpost', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_userpost_user_id_user'), 'userpost', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_userpost_user_id_user'), 'userpost', type_='foreignkey')
    op.drop_column('userpost', 'user_id')
    # ### end Alembic commands ###
