import os

SQLALCHEMY_DATABASE_HOST = os.environ.get('SQLALCHEMY_DATABASE_HOST', default='localhost:5432')
SQLALCHEMY_DATABASE_PASS = os.environ.get('SQLALCHEMY_DATABASE_PASS', default='postgres')
SQLALCHEMY_DATABASE_USER = os.environ.get('SQLALCHEMY_DATABASE_USER', default='postgres')
SQLALCHEMY_DATABASE_NAME = os.environ.get('SQLALCHEMY_DATABASE_NAME', default='postgres')

SQLALCHEMY_DATABASE_URI = f'postgresql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASS}@{SQLALCHEMY_DATABASE_HOST}/{SQLALCHEMY_DATABASE_NAME}'

SQLALCHEMY_TRACK_MODIFICATIONS = False